apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tempo-values-sm
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretmanager
    kind: ClusterSecretStore
  target:
    name: tempo-values
    creationPolicy: Owner
    template:
      data:
        values.yaml: "{{ .config | fromJson | toYaml }}"
  data:
    - secretKey: config
      remoteRef:
        key: main
        property: tempo-values.yaml
