replicaCount: 1
resources:
  limits:
    memory: "3Gi"
    cpu: "1"
  requests:
    memory: "1.5Gi"
    cpu: "500m"

storage:
  enabled: true
  size: 400Gi
  className: gp2

image:
  repository: samvera/fcrepo4
  pullPolicy: IfNotPresent
  tag: 4.7.5

postgresql:
  enabled: false
externalPostgresql:
  host: CHANGEME
  username: CHANGEME
  password: CHANGEME

s3:
  enabled: true
  bucket: CHANGEME
  access_key: CHANGEME
  secret_key: CHANGEME
