apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mysql-tilma-dev
  name: mysql-tilma-dev-shared-efs
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 101Gi
  storageClassName: efs-sc
  volumeName: mysql-tilma-dev-shared-efs
