---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-tilma-dev-shared-efs
spec:
  capacity:
    storage: 101Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  volumeMode: Filesystem
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0d90713bb84754a4d:/tilma
