apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: crowdsec-values-sm
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretmanager
    kind: ClusterSecretStore
  target:
    name: crowdsec-values
    creationPolicy: Owner
    template:
      data:
        values.yaml: "{{ .config | fromJson | toYaml }}"
  data:
   - secretKey: config
     remoteRef:
       key: main
       property: crowdsec-values.yaml
