apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fcrepo-values-sm
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretmanager
    kind: ClusterSecretStore
  target:
    name: fcrepo-values
    creationPolicy: Owner
  data:
   - secretKey: values.yaml
     remoteRef:
       key: fcrepo-values
