# values.yaml
replicaCount: 2
collectionReplicas: 1
image:
  tag: 8.11.1-debian-10-r31
authentication:
  enabled: true
  adminUsername: admin
  adminPassword: CHANGEME
javaMem: "-Xms4g -Xmx6g"
resources:
  limits:
    memory: 8Gi
  requests:
    memory: 4Gi
zookeeper:
  replicaCount: 3
  env:
    JVMFLAGS: "-Xms512m -Xmx1g"
  resources:
    limits:
      memory: 1Gi
    requests:
      memory: 512Mi
persistence:
  enabled: true
  storageClass: gp2
  size: 500Gi
extraVolumeMounts:
  - name: backup
    mountPath: /backup
    readOnly: false
extraVolumes:
  - name: backup
    persistentVolumeClaim:
      claimName: solr-backup
