apiVersion: mariadb.mmontes.io/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-dev
spec:
  rootPasswordSecretKeyRef:
    name: mariadb-dev
    key: password

  database: mariadb
  username: mariadb
  passwordSecretKeyRef:
    name: mariadb-dev
    key: password

  image: mariadb:11.0.3

  port: 3306

  replicas: 2

  replication:
    enabled: true

  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - topologyKey: "kubernetes.io/hostname"

  tolerations:
    - key: "mariadb.mmontes.io/ha"
      operator: "Exists"
      effect: "NoSchedule"

  podDisruptionBudget:
    maxUnavailable: 66%

  updateStrategy:
    type: RollingUpdate

  myCnf: |
    [mariadb]
    bind-address=*
    default_storage_engine=InnoDB
    binlog_format=row
    innodb_autoinc_lock_mode=2
    max_allowed_packet=512M
    symbolic-links=0
    # UTF8
    character-set-client-handshake = FALSE
    character-set-server = utf8mb4
    collation-server = utf8mb4_unicode_ci

    [mysqldump]
    max_allowed_packet=512M

  volumeClaimTemplate:
    resources:
      requests:
        storage: 1Ti
    accessModes:
      - ReadWriteOnce

  resources:
    requests:
      cpu: '2'
      memory: 16Gi
    limits:
      cpu: '4'
      memory: 24Gi
  metrics:
    exporter:
      image: prom/mysqld-exporter:v0.14.0
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 300m
          memory: 512Mi
    serviceMonitor:
      prometheusRelease: cattle-monitoring-system
      interval: 10s
      scrapeTimeout: 10s
