apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: efs-values-sm
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretmanager
    kind: ClusterSecretStore
  target:
    name: efs-secret
    creationPolicy: Owner
  data:
    - secretKey: aws_access_key_id
      remoteRef:
        key: main
        property: efs-secret.aws_access_key_id
    - secretKey: aws_secret_access_key
      remoteRef:
        key: main
        property: efs-secret.aws_secret_access_key
