apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: efs-values-sm
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretmanager
    kind: ClusterSecretStore
  target:
    name: efs-secret
    creationPolicy: Owner
  data:
    - secretKey: config
      remoteRef:
        key: main
        property: efs-secret
