apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: crowdsec-api-sm
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretmanager
    kind: ClusterSecretStore
  target:
    name: crowdsec-api-key
    creationPolicy: Owner
    template:
      data:
        value: "{{ .conf | fromJson | toYaml }}"
  data:
   - secretKey: conf
     remoteRef:
       key: main
       property: crowdsec-api-key
