loki:
  auth_enabled: false
nameOverride: loki
serviceMonitor:
  enabled: true
backend:
  resources:
    requests:
      memory: 250Mi
      cpu: 1m
    limits:
      memory: 500Mi
      cpu: 2m
gateway:
  resources:
    requests:
      memory: 120Mi
      cpu: 1
    limits:
      memory: 240Mi
      cpu: 2
