loki:
  auth_enabled: false
nameOverride: loki
serviceMonitor:
  enabled: true
backend:
  resources:
    requests:
      memory: 250Mi
      cpu: 10m
    limits:
      memory: 500Mi
      cpu: 20m
gateway:
  resources:
    requests:
      memory: 120Mi
      cpu: 10m
    limits:
      memory: 240Mi
      cpu: 20m
grafana-agent-operator:
  resources:
    requests:
      memory: 350Mi
      cpu: 10m
    limits:
      memory: 500Mi
      cpu: 20m
read:
  resources:
    requests:
      memory: 1500Mi
      cpu: 150m
    limits:
      memory: 3000Mi
      cpu: 300m
