loki:
  auth_enabled: false
nameOverride: loki
serviceMonitor:
  enabled: true
backend:
  resources:
    requests:
      memory: 250Mi
      cpu: 10m
    limits:
      memory: 500Mi
      cpu: 20m
gateway:
  resources:
    requests:
      memory: 120Mi
      cpu: 10m
    limits:
      memory: 240Mi
      cpu: 20m
