apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-sm
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretmanager
    kind: ClusterSecretStore
  target:
    name: github
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      metadata:
        annotations:
          replicator.v1.mittwald.de/replicate-to: .*
  data:
   - secretKey: .dockerconfigjson
     remoteRef:
       key: main
       property: github-docker
