apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-sm
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretmanager
    kind: ClusterSecretStore
  target:
    name: github
    creationPolicy: Owner
  data:
   - secretKey: .dockerconfigjson
     remoteRef:
       key: github-docker
